m1=int(input("enter mark 1\n"))
m2=int(input("enter mark 2\n"))
m3=int(input("enter mark 3\n"))
m4=int(input("enter mark 4\n"))
m5=int(input("enter mark 5\n"))
total=m1+m2+m3+m4+m5
avg=total/5
print("mark1=",m1)
print("mark2=",m2)
print("mark3=",m3)
print("mark4=",m4)
print("mark4=",m5)
print("total=",total)
print("avg mark=",avg)